### ISSUE TITLE
Module aanmaken

### ISSUE THREAD

**Issue by jaelkwakkel** [Windesheim-HBO-ICT/Leerlijn-Wiki#10]
### Discussed in https://github.com/Windesheim-HBO-ICT/Leertaken/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **Jasperswag03** April 13, 2024</sup>
### **module aanmaken**
Korte tutorial voor het aanmaken van een module voor de wiki.

**Begin wiki project**
Voor het aanmaken van een wiki project [startup wiki](https://docs.requarks.io/en/dev).

Voor project opnieuw opstarten: kill bash, nieuwe bash en opnieuw yarn dev.

**module toevoegen**
Ga naar server/modules.
Kies een module [type](https://docs.requarks.io/dev/modules).
Zet in de folder met dezelfde naam als het type module een folder met de custum module. 
Daarin horen deze 2 bestanden. In dit geval een module van het type storage:

```js storage.js
/* global WIKI */

module.exports = {
  async activated () {

  },
  async deactivated () {

  },
  async init () {
    WIKI.logger.warn('aangezet naam is: ' + this.config.naam + ' andere var was: ' + this.config.leeftijd)
  },
  async created (page) {

  },
  async updated (page) {

  },
  async deleted (page) {

  },
  async renamed (page) {

  },
  async sync () {

  }
}
```

* WIKI.logger om bij de logger te komen
* this.config.[propnaam] om bij de props van het yml bestand te komen

```yml defenition.yml
key: aWindesheim
title: A windesheim opslagsolutie
description: een korte beschrijving van de module
author: Windesheim-ict
logo: https://media.graphassets.com/ddDDGPriQHC1OyGYRAKO
website: https://www.fortnite.com/
isAvailable: true
supportedModes:
    - push
defaultMode: push
schedule: false
props:
  naam: String
  leeftijd: Number
actions:
  - handler: eersteActie
    label: label van de actie
    hint: hint van de actie over wat dit doet
```

* Key moet hetzelfde zijn als de naam van de folder.
* actions staan verkeerd op de website, de juiste indent is zoals in dit voorbeeld.

</div>
